services:
  - type: web
    name: tropicana
    runtime: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "24"
      - key: NODE_ENV
        value: production

      # Firebase Admin (backend)
      - key: FIREBASE_ADMIN_PROJECT_ID
        value: sitio-web-cb0c4
      - key: FIREBASE_ADMIN_CLIENT_EMAIL
        value: yamiklunder@sitio-web-cb0c4.iam.gserviceaccount.com
      - key: FIREBASE_ADMIN_PRIVATE_KEY
        sync: false

      # Firebase Frontend (Vite)
      - key: VITE_FIREBASE_API_KEY
        value: AIzaSyDYp6WBRVP1-UqjQxA_yxpcJYobqeRcNdU
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: sitio-web-cb0c4.firebaseapp.com
      - key: VITE_FIREBASE_PROJECT_ID
        value: sitio-web-cb0c4
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: sitio-web-cb0c4.firebasestorage.app
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: "776506266227"
      - key: VITE_FIREBASE_APP_ID
        value: 1:776506266227:web:931ee6c5bc30c5cd041006
      - key: VITE_FIREBASE_ADMIN_UID
        sync: false
      - key: VITE_ADMIN_UID
        sync: false
      - key: VITE_API_BASE_URL
        value: https://tropimahuix-web.onrender.com
      - key: API_BASE_URL
        value: https://tropimahuix-web.onrender.com

      # PayPal
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_MODE
        value: sandbox
      - key: PAYPAL_CURRENCY
        value: MXN
